### ISSUE TITLE
Problem installing the module in npm

### ISSUE THREAD

**Issue by jch02140** [jaywilz/react-bootstrap-country-select#1]
I tried to run npm install react-bootstrap-country-select under my project directory and got the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: currency-app@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-bootstrap-country-select@0.7.11
npm ERR! node_modules/react-bootstrap-country-select
npm ERR!   react-bootstrap-country-select@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\******\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\******\AppData\Local\npm-cache\_logs\2020-12-31T21_07_51_309Z-debug.log
```

Any help is appreciated...

**Comment by jaywilz** [comment]
Which npm version are you using? As a quick fix you could try using the `--legacy-peer-deps` flag?

I'll also update the version of the react peer dependancy in react-bootstrap-country-select's package.json to `>=16.8`.

**Comment by jch02140** [comment]
I am using npm v7.3.0. 

I was able to install with the --force option though it gives out some warning errors... Otherwise, it seems everything else is working as intended...

**Comment by jaywilz** [comment]
This should now be fixed in version react-bootstrap-country-select@0.7.12.

Thanks for reporting the issue!

**Comment by kirkglpro** [comment]
@jaywilz I am facing similar issue with react-bootstrap-country-select": "^1.0.0". How do i fix this?

Resolving node version 16.x...
remote:        Downloading and installing node 16.15.1...
remote:        Using default npm version: 8.11.0
 npm ERR! code ERESOLVE
remote:        npm ERR! ERESOLVE could not resolve
remote:        npm ERR!
remote:        npm ERR! While resolving: react-bootstrap-country-select@1.0.0
remote:        npm ERR! Found: react@16.13.1
 npm ERR! Conflicting peer dependency: react@18.2.0
remote:        npm ERR! node_modules/react
remote:        npm ERR!   peer react@">=17.0.2" from react-bootstrap-country-select@1.0.0
remote:        npm ERR!   node_modules/react-bootstrap-country-select
remote:        npm ERR!     react-bootstrap-country-select@"^1.0.0" from the root project

**Comment by zhoub** [comment]
Same issue here
