### ISSUE TITLE
Issue installing and building

### ISSUE THREAD

**Issue by kirkglpro** [jaywilz/react-bootstrap-country-select#13]
@jaywilz  I am facing an issue with react-bootstrap-country-select": "^1.0.0". How do i fix this?

Works locally, however, when i try to deploy to heroku it fails.

Resolving node version 16.x...
remote: Downloading and installing node 16.15.1...
remote: Using default npm version: 8.11.0
npm ERR! code ERESOLVE
remote: npm ERR! ERESOLVE could not resolve
remote: npm ERR!
remote: npm ERR! While resolving: react-bootstrap-country-select@1.0.0
remote: npm ERR! Found: react@16.13.1
npm ERR! Conflicting peer dependency: react@18.2.0
remote: npm ERR! node_modules/react
remote: npm ERR! peer react@">=17.0.2" from react-bootstrap-country-select@1.0.0
remote: npm ERR! node_modules/react-bootstrap-country-select
remote: npm ERR! react-bootstrap-country-select@"^1.0.0" from the root project

**Comment by jaywilz** [comment]
Do you need to be using react@16.13.1?

What happens if you specify react 17 in your package.json?

**Comment by kirkglpro** [comment]
@jaywilz I tried with 17 as well. I get the same error.

**Comment by kirkglpro** [comment]
@jaywilz I was able to resolve by downgrading 
node to v12.14.1
npm to 6.13.4

Not sure why it fails on 16 or higher

**Comment by kirkglpro** [comment]
Closing this issue
