### ISSUE TITLE
Erro import librery  contrySelect

### ISSUE THREAD

**Issue by mauriciocartagena** [jaywilz/react-bootstrap-country-select#6]
import CountrySelect from "react-bootstrap-country-select";

I have next problem

Could not find a declaration file for module 'react-bootstrap-country-select'. '/React-2-comfeco/node_modules/react-bootstrap-country-select/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-bootstrap-country-select` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-bootstrap-country-select';`ts(7016)

**Comment by jaywilz** [comment]
A TypeScript declaration is now included in version 1.0.0.
